### DISCUSSION TITLE
Full screen + landscape CSS is here!

### DISCUSSION THREAD

**Discussion by annappropriate** [st3v3nmw/obsidian-spaced-repetition#990] [General]
The gap on top of the screen drives me nuts. I don't have that much screen space to afford fancy gaps :sweat_smile:  

This is the CSS behind it: https://github.com/st3v3nmw/obsidian-spaced-repetition/blob/ca4c2617770f047472fd30fe242f4520eb635b32/styles.css#L1-L6

If you want to get rid of the gap, save and enable this snippet:
```css
.is-phone #sr-modal {
    height: 100% !important;
    width: 100% !important;
    max-width: 100%;
    max-height: 100%;
    margin: 0px !important;
}
```

No more gap! It's free real estate!

Happy learning :smiling_face_with_three_hearts:

**Comment by annappropriate** [comment]
After spending another hour on it, I'm happy to present a full screen + landscape mode CSS.

```css
.is-phone #sr-modal {
    height: 100% !important;
    width: 100% !important;
    max-width: 100%;
    max-height: 100%;
    padding-top: 0px;
}

@media only screen and (min-device-width: 480px) and (orientation: landscape) {
    .is-phone .sr-flashcard {
        flex-direction: row;
    }

    .is-phone .sr-header {
        flex-direction: column;
        flex: 0 1 0;
    }

    .is-phone .sr-content {
        flex: 1 0 0;
    }

    .is-phone .sr-response {
        flex-direction: column;
        flex: 0 1 0;
    }

    .is-phone .sr-controls {
        flex-direction: column;
    }

    .is-phone .sr-title {
        display: none;
    }

    .is-phone .sr-response-button {
        writing-mode: vertical-lr;
    }
}
```

Pretty neat.

**Comment by ronzulu** [comment]
Hi @annappropriate sounds good  - I only use Obsidian on the desktop, so I haven't tried this out myself.

I'm wondering if you think this should be updated in the code itself? 
Do you think some users would prefer the current layout? 
Is the ideal to make this a user configurable setting?

**Reply by DDPF02** [reply]
Is this also possible on the desktop? I would love to have a full screen review window.

**Reply by annappropriate** [reply]
Hi @DDPF02, of course!
This CSS should get you full screen on any device:
```css
#sr-modal {
    height: 100% !important;
    width: 100% !important;
    max-width: 100%;
    max-height: 100%;
    padding-top: 0px;
}
```
