### ISSUE TITLE
[Bug]: iOS Flashcard Review Page Close Icon Difficult to Press

### ISSUE THREAD

**Issue by highb** [st3v3nmw/obsidian-spaced-repetition#1133]
### Describe the bug

The "x" in the upper right hand corner to close the review screen is very difficult to press on iOS. I'm unsure if this is a problem with the new iPhone 16 bezel size or the "dynamic island". On a 2024 iPad Pro, it isn't as big of an issue.

### To Reproduce

1. Use iOS on an iPhone.
2. Review flashcards

### Expected behavior

I would expect the close icon to be somewhere that isn't so close to the edge of the screen/buried under my top icons so that I can actually tap it.

### Screenshots

Will post these in a moment

### OS of your device

18.0

### Obsidian version

1.6.7

### Plugin version

1.13.1

**Comment by BashirAljounaidy** [comment]
#### 1. **Locate the `.obsidian` Folder:**
   - Open File Explorer.
   - Navigate to the folder where your Obsidian vault is stored.
   - Inside your vault folder, locate the `.obsidian` folder. If you don’t see it, make sure **hidden items** are enabled:
     - Go to the **View** tab in File Explorer.
     - Check the box for **Hidden items**.

#### 2. **Create a `snippets` Folder (if it doesn’t exist):**
   - Open the `.obsidian` folder.
   - Check for a folder named `snippets`. If it doesn’t exist:
     - Right-click and select **New > Folder**.
     - Name the folder `snippets`.

#### 3. **Create a CSS File:**
   - Open a text editor like **Notepad** or **VS Code**.
   - Write or paste your CSS code. Example:
     ```css
     /* Make modal close button larger and adjust position */
     #sr-modal .modal-close-button {
         z-index: 21;
         top: 60px !important; /* Position it slightly lower */
         left: 15px !important; /* Move to the left */
         position: absolute !important; /* Ensure proper positioning */
         font-size: 32px !important; /* Increase the font size */
         padding: 10px 20px !important; /* Add padding for clickability */
         border-radius: 8px !important; /* Rounded corners */
     }

     #sr-modal .sr-modal-content {
         margin-top: 50px;
         margin-bottom: 20px; /* Add bottom margin */
     }
     ```

   - Save the file with a `.css` extension (e.g., `custom-style.css`) in the `snippets` folder.

#### 4. **Enable the Snippet in Obsidian:**
   - Open Obsidian.
   - Go to **Settings > Appearance > CSS Snippets**.
   - Find the snippet file (e.g., `custom-style`).
   - Toggle it **on** to apply.

---
