### ISSUE TITLE
Spaced repetition does not work on Android

### ISSUE THREAD

**Issue by aaronstarky** [st3v3nmw/obsidian-spaced-repetition#1171]
I really love this plugin and would like to be able to do my flashcards on my phone. unfortunately, the UI is too small to be able to be used on phones. Please help!

**Comment by MostlyArmless** [comment]
Fortunately we can fix this ourselves with some CSS. Create a file in your vault's `.obsidian/snippets/` folder called `fix-flashcard-modal.css` and paste this in:
```css
.modal#sr-modal {
  width: 100vw !important;
  max-width: 100vw !important;
  height: 100vh !important;
  max-height: 100vh !important;
  margin: 0 !important;
  position: fixed !important;
  left: 50% !important;
  top: 50% !important;
  transform: translate(-50%, -50%) !important;
}
```

Then restart Obsidian, go to Obsidian's settings --> Appearance tab, scroll all the way down and turn on the toggle for the CSS file you just added. All the flashcard popup dialogs should now entirely fill the screen.
