### ISSUE TITLE
[Bug]: Close Button Overlap in iOS

### ISSUE THREAD

**Issue by msudgh** [st3v3nmw/obsidian-spaced-repetition#1178]
The close button (X) overlaps with the battery status and indicators, making it difficult to tap.

Fix Suggestion:
Add padding or adjust constraints to respect the safe area.

Attachment: Screenshot included.

### To Reproduce

1. Open the app.
2. Navigate to the “Decks” screen.
3. Observe the close button placement.

### Expected behavior

The button should be below of the system status indicators.

### Screenshots

![IMG_5948](https://github.com/user-attachments/assets/165d5b8c-48f7-43da-9354-29ee02b2cf6f)

### OS of your device

iOS

### Obsidian version

18

### Plugin version

1.13.2

**Comment by prtksxna** [comment]
Similar to #1133

**Comment by BashirAljounaidy** [comment]
it takes me 4 hours but this is a solve 
#### 1. **Locate the `.obsidian` Folder:**
   - Open File Explorer.
   - Navigate to the folder where your Obsidian vault is stored.
   - Inside your vault folder, locate the `.obsidian` folder. If you don’t see it, make sure **hidden items** are enabled:
     - Go to the **View** tab in File Explorer.
     - Check the box for **Hidden items**.

#### 2. **Create a `snippets` Folder (if it doesn’t exist):**
   - Open the `.obsidian` folder.
   - Check for a folder named `snippets`. If it doesn’t exist:
     - Right-click and select **New > Folder**.
     - Name the folder `snippets`.

#### 3. **Create a CSS File:**
   - Open a text editor like **Notepad** or **VS Code**.
   - Write or paste your CSS code. Example:
     ```css
     /* Make modal close button larger and adjust position */
     #sr-modal .modal-close-button {
         z-index: 21;
         top: 60px !important; /* Position it slightly lower */
         left: 15px !important; /* Move to the left */
         position: absolute !important; /* Ensure proper positioning */
         font-size: 32px !important; /* Increase the font size */
         padding: 10px 20px !important; /* Add padding for clickability */
         border-radius: 8px !important; /* Rounded corners */
     }

     #sr-modal .sr-modal-content {
         margin-top: 50px;
         margin-bottom: 20px; /* Add bottom margin */
     }
     ```

   - Save the file with a `.css` extension (e.g., `custom-style.css`) in the `snippets` folder.

#### 4. **Enable the Snippet in Obsidian:**
   - Open Obsidian.
   - Go to **Settings > Appearance > CSS Snippets**.
   - Find the snippet file (e.g., `custom-style`).
   - Toggle it **on** to apply.

---
