### ISSUE TITLE
Mobile Rendering problems

### ISSUE THREAD

**Issue by l1mey112** [st3v3nmw/obsidian-spaced-repetition#1264]
![image](https://github.c
om/user-attachments/assets/fef0ca78-b8a3-43ef-a183-207eb828bdb1)

Q.E.D.

**Comment by l1mey112** [comment]
Thank you.

**Comment by IgorKrupenja** [comment]
Another way:

1. Keep "Open in a new tab" disabled.
2. Add this to `.obsidian/snippets/custom.css`:

```css
#sr-modal {
  width: 90% !important;
  max-width: 100% !important;
}
```

**Comment by l1mey112** [comment]
Is there a way to only make that CSS run on mobile?

**Comment by IgorKrupenja** [comment]
One option would be to use a media query. Adjust the `max-width` value in pixels based on your device screen width:

```css
@media only screen and (max-width: 1000px) {
  #sr-modal {
    width: 90% !important;
    max-width: 100% !important;
  }
}
```
