### ISSUE TITLE
[BUG] Cloze card are not working

### ISSUE THREAD

**Issue by insanitywanted** [st3v3nmw/obsidian-spaced-repetition#421]
**Describe the bug**
Cloze cards are not working

**To Reproduce**

1. Create a card
2. Use ==highlights== or **bolded text** to create a cloze deletion

**Expected behavior**
Cloze deletion card

**Screenshots**
If applicable, add screenshots to help explain the bug. This could be the logs in the developer console (`CTRL` + `SHIFT` + `i`).
![Screenshot 2022-03-15 at 5 06 17 PM](https://user-images.githubusercontent.com/47140829/158370203-70f2fdd5-bfee-42a9-a08c-838cd2ebf2cd.png)
![Screenshot 2022-03-15 at 5 10 00 PM](https://user-images.githubusercontent.com/47140829/158370332-842df9e5-56f7-4bbc-a9bd-046f12d84626.png)

**Versions (please complete the following information):**

-   OS: Latest MacOS
-   Obsidian version: 0.13.33
-   Plugin version: Latest
-   If on desktop, Installer version: [run `this.navigator.appVersion` on the developer console, e.g. `5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/0.12.3 Chrome/89.0.4389.128 Electron/12.0.6 Safari/537.36"`]

**Additional context**
Add any other context about the problem here (e.g. the markdown producing the error).

**Comment by harmtemolder** [comment]
Not sure if this works with every theme, but I fixed this by saving the following as `vault/.obsidian/snippets/Spaced Repetition.css` and enabling it under Settings > Appearance:

```css
#sr-flashcard-view mark {
  background-color: var(--text-normal);
  color: var(--text-normal);
}

#sr-flashcard-view mark:hover {
  background-color: var(--background-secondary-alt);
  color: var(--text-on-selection);
}
```
